### ISSUE TITLE
Support composite tokens

### ISSUE THREAD

**Issue by Heydon** [Heydon/design-tokens-cli#2]
* See https://design-tokens.github.io/community-group/format/#composite-types
* Objects and arrays or just objects support?
* Need to change "flattening" logic to handle non-simple (string) `$value`s

**Comment by pwang2** [comment]
@Heydon , have you found any alternative to support this? Thanks. 

[Example 23](https://design-tokens.github.io/community-group/format/#example-advanced-composite-token-example) will result as 
![image](https://user-images.githubusercontent.com/1592014/201766074-68e16b69-cfc4-4d43-bf43-54fa9fcc31b4.png)
