### ISSUE TITLE
globalPrefix undefined

### ISSUE THREAD

**Issue by joenarus** [Heydon/design-tokens-cli#6]
Hi! I came across this repository today and I'm tinkering around with it and it's pretty awesome!

I've found one small issue so far: 
If no globalPrefix is added to the config, tokens are generated with `undefined-` ahead of them.

**Comment by Heydon** [comment]
@joenarus whoops! I thought I'd handled that. Will look today.

**Comment by Heydon** [comment]
OKay, I've fixed this in `v0.0.6`
